global:
  scrape_interval: 15s

scrape_configs: 
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'Testing Environment'
    static_configs:
    - targets: ['157.175.182.159:9100']

  - job_name: 'postgres-rds'
    static_configs:
    - targets: ['host.docker.internal:9187']

  # Local Container for test
  - job_name: 'Local Container'
    static_configs:
    - targets: ['172.17.0.2']

  - job_name: '.NET Api Test-Env'
    static_configs:
    - targets: ['157.175.182.159:8080']

