apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eco-ingress
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"  # Force SSL redirect
    prometheus.io/scrape: "true"      # Enable Prometheus scraping
    prometheus.io/port: "PORT"        # Replace with actual port
    prometheus.io/path: "/metrics"    # Path to scrape metrics 
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - www.ecopowerhub.com
        - api.ecopowerhub.com
        - prometheus.ecopowerhub.com
        - grafana.ecopowerhub.com
      secretName: ecopower-tls-secret
  rules:
  - host: www.ecopowerhub.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eco-nginx-service
            port:
              number: 80  
  - host: api.ecopowerhub.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eco-backend-service
            port:
              number: 80  
  - host: prometheus.ecopowerhub.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-kube-prometheus-prometheus
            port:
              number: 9090
  - host: grafana.ecopowerhub.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 80